### ISSUE TITLE
Crash with security craft

### ISSUE THREAD

**Issue by ghost** [BluSpring/Kilt#100]
### Version information

Kilt-0.0.1+mc1.20.1+build.709575

### Reproduction Steps

1. Put kilt and its dependencies on the mods folder
2. put security craft jar on the mods folder
3. start the game
4. try to create a singleplayer world

### Java version

Java 17

### Crash Report file

[crash-2024-12-08_17.08.33-client.txt](https://github.com/user-attachments/files/18054171/crash-2024-12-08_17.08.33-client.txt)

### Additional information

![image](https://github.com/user-attachments/assets/d4896dc5-4bc7-4b32-ba1f-ab4c5b652099)
![image](https://github.com/user-attachments/assets/da5c39a1-3c89-49a3-93a4-d8b8a8bf8676)

And i tried to use the fabric loader 0.16.8 too and it doesnt work.

**Comment by kirpi4ek** [comment]
try remove indium or try all versions of indium.
try all versions of sodium.

**Comment by Cartrigger** [comment]
https://mclo.gs/cy3xVI5

**Comment by kirpi4ek** [comment]
@Cartrigger
![image](https://github.com/user-attachments/assets/4f3146c0-f6c2-4b61-923c-45a2ead438d0)
![image](https://github.com/user-attachments/assets/bface0a8-7828-421d-bce4-205b19a61925)
maybe security craft is not fabric?

**Comment by ghost** [comment]
Security craft isnt fabric, i tried with indium and without indium and yes, with another sodium versions and still doesnt work

**Comment by Cartrigger** [comment]
@kirpi4ek no crap, its forge, this is kilt.

it is broken with the newest commit, the last one (https://github.com/KiltMC/Kilt/actions/runs/12049589233) works

(https://mclo.gs/L7xah2i) (fully working)

**Comment by Cartrigger** [comment]
https://mclo.gs/UEsojir
Newest Commit, it starts now I guess, but it fails during server load

**Comment by Cartrigger** [comment]
https://mclo.gs/Uc3b4eQ
Newest Commit again

**Comment by ghost** [comment]
**Hey guys i found a way to make it work.** It seems like the api of security craft and some things changed a bit on the v1.9.12 making it crash.
I tried with the v1.9.11 and works just fine

**Comment by BluSpring** [comment]
Try the latest build again, it should be fixed now.

**Comment by Cartrigger** [comment]
https://mclo.gs/I6GKRcM
Fixed!

**Comment by ghost** [comment]
**Yay** it works now :D!
everything works as expected, but one thing; the fake lava and fake water bucket doesnt work properly
let me open an issue.
