### ISSUE TITLE
Kilt crashes without sodium

### ISSUE THREAD

**Issue by scarabx** [BluSpring/Kilt#108]
### Version information

Kilt-0.0.1 +mc1.20.1+build.8f97cf.jar

### Reproduction Steps

Install listed mods.
Launch game.
Game crashes bc of no sodium and indium.

### Java version

Java 17

### Crash Report file

https://mclo.gs/MpwlUd2

### Additional information

fabric-api-0.92.2+1.20.1.jar
fabric-language-kotlin-1.13.0+kotlin.2.1.0.jar
architectury-9.2.14-fabric.jar
ForgeConfigAPIPort-v8.0.1-1.20.1-Fabric.jar
Cloth-Config.jar
Ferrite-Core.jar
Immediatelyfast.jar
Krypton.jar
Lithium.jar
ModernFix.jar
modmenu-7.2.2.jar
Server-Core.jar
Simple-Voice-Chat.jar
Vivecraft.jar

I want to be able to use kilt without sodium as the forge mods I want to install conflicts with sodium.

**Comment by BluSpring** [comment]
This is intentional, as there is currently a really severe rendering bug without Sodium installed, so I have made Sodium a dependency temporarily.

Please make a new issue that refers to which Forge mods are conflicting with Sodium.
