### ISSUE TITLE
Kilt crashes with Sodium 0.5.9+

### ISSUE THREAD

**Issue by hu-ja-ja** [BluSpring/Kilt#14]
### Version information

Kilt-0.0.1+mc1.20.1+build.abce57

### Reproduction Steps

1, Add Kilt and it's required mods (Architectury, Fabric API, Fabric Language Kotlin, Forge Config API Port).
2, Add Sodium 0.5.9 or 0.5.10.
3, Launch.

### Java version

Eclipse Adoptium jdk-17.0.10.7

### Crash Report file

Only Sodium
https://gist.github.com/hu-ja-ja/c64da20852eb418188c53263dc6456a2

With Indium
https://gist.github.com/hu-ja-ja/828ccdb28ee10f041199b325972a191e

### Additional information

This crash did not occur in Sodium 0.5.8 (With Indium) or Embeddium Fabric 0.3.21.
Adding Indium did not change this.
Running in Prism Launcher.

I know it is hard work to operate a project like this, but good luck!

**Comment by BluSpring** [comment]
Try 4241f4a49b2a7ba83419c1b5404f74473cbe9b8b, this should be fixed now
