### ISSUE TITLE
SecurityCraft Crashes

### ISSUE THREAD

**Issue by Cartrigger** [BluSpring/Kilt#15]
### Version information

[1.20.1] SecurityCraft v1.9.10

### Reproduction Steps

Start the game, press single player.

### Java version

Java 21

### Crash Report file

https://mclo.gs/rWfNEJI

Full Log: https://mclo.gs/pl3KVaP

### Additional information

Resources also reload improperly making all fonts show boxes.

**Comment by BluSpring** [comment]
Do you mind sending the full log? Currently not enough information for me here

**Comment by Cartrigger** [comment]
> Do you mind sending the full log? Currently not enough information for me here

Just updated the report to have the full log.

**Comment by BluSpring** [comment]
i'm not actually sure why SecurityCraft isn't working, considering this works fine in my dev env...

![image](https://github.com/KiltMC/Kilt/assets/20620191/e29d8fd8-1af0-47ec-aa5e-e652bdfd3f46)

**Comment by Cartrigger** [comment]
Must be a edge case within non dev env's, ill try loading with sodium (non embeddium)

**Comment by Cartrigger** [comment]
[latest.log](https://github.com/user-attachments/files/16092919/latest.log)
[crash-2024-07-03_23.22.09-client.txt](https://github.com/user-attachments/files/16092920/crash-2024-07-03_23.22.09-client.txt)

**Comment by Cartrigger** [comment]
[latest.log](https://github.com/user-attachments/files/16102659/latest.log)
[crash-2024-07-04_15.53.15-client.txt](https://github.com/user-attachments/files/16102661/crash-2024-07-04_15.53.15-client.txt)
newest action as of now
