### ISSUE TITLE
Incompatible with SlashBladeResharped

### ISSUE THREAD

**Issue by windy664** [BluSpring/Kilt#17]
### Version information

Kilt-0.0.1+mc1.20.1+build.1efb23

### Expected Behavior

can play

### Actual Behavior

As I created the world , it crashed.

### Reproduction Steps

1.put architectury-9.2.14-fabric.jar
fabric-api-0.92.1+1.20.1.jar
fabric-language-kotlin-1.11.0+kotlin.2.0.0.jar
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
Kilt-0.0.1+mc1.20.1+build.1efb23.jar
[拔刀剑2]SlashBladeResharped-1.20.1-0.7.0.jar
into the mods
2. Start the game

### Java version

19.0.2, Amazon.com Inc.

### Additional information

[crash-2024-07-13_16.13.52-client.txt](https://github.com/user-attachments/files/16201381/crash-2024-07-13_16.13.52-client.txt)

**Comment by BluSpring** [comment]
Remapper issue, need to fix it again
