### ISSUE TITLE
Cobblefordays doesn't work at all

### ISSUE THREAD

**Issue by lzm11111111** [BluSpring/Kilt#25]
### Version information

latest+1.20.1

### Expected Behavior

It should rendered correctly and works

### Actual Behavior

It doesn't works and rendered incorrectly

### Reproduction Steps

https://modrinth.com/mod/cobblefordays
When have Cobblefordays installed, the game won't crash, but the behavior is broken, the cobblestone generator doesn't rendered correctly and it doesn't work at all

### Java version

17

**Comment by BluSpring** [comment]
Could you send a log file?

**Comment by lzm11111111** [comment]
> Could you send a log file?

[latest.log](https://github.com/user-attachments/files/17275693/latest.log)

**Comment by BluSpring** [comment]
Okay, this one's new, will look into this later

**Comment by lzm11111111** [comment]
> Okay, this one's new, will look into this later

Game won't crash, but the behavior will broken.
