### ISSUE TITLE
Aquaculture 2 incompatible

### ISSUE THREAD

**Issue by lzm11111111** [BluSpring/Kilt#28]
### Version information

latest+1.20.1

### Reproduction Steps

1. Installing aquaculture 2
2. Create a world
3. Crash the game

### Java version

17

### Crash Report file

[crash-2024-10-08_15.25.20-client.txt](https://github.com/user-attachments/files/17289525/crash-2024-10-08_15.25.20-client.txt)

**Comment by BluSpring** [comment]
I already fixed this, get the latest Kilt build from the Actions.
