### ISSUE TITLE
Permission to re-upload to Modrinth

### ISSUE THREAD

**Issue by flikrheist** [BluSpring/Kilt#45]
Hi, do I have permission to reupload KiltMC to Modrinth? I'd be happy to discuss any matters with you.

Thanks for your time,
flikrheist

**Comment by BluSpring** [comment]
No, you absolutely do not.

This is a WIP mod that **should not be readily released in its current state**.
I will upload it __myself__ when it is ready, and at the moment, it absolutely is not.

**Comment by flikrheist** [comment]
@BluSpring | Can I make it Unlisted or Private?

**Comment by BluSpring** [comment]
No, what on earth are you doing that requires this?

**Comment by flikrheist** [comment]
Just to make it easier to download.

**Comment by BluSpring** [comment]
We have [Nightly.link](https://nightly.link/KiltMC/Kilt/workflows/gradle/1.20.1/Kilt%20Build%20JARs) for this purpose.

**Comment by flikrheist** [comment]
Ok, thx ill delete it.
