### ISSUE TITLE
Use the Engineer's manual in Immersive Engineering and the game crashes right away

### ISSUE THREAD

**Issue by gdsfdsggd** [BluSpring/Kilt#46]
### Version information

Kilt-0.0.1+mc1.20.1+build.32429c

### Reproduction Steps

Crashes using the engineer's manual

### Java version

java17

### Crash Report file

[错误报告-2024-10-25_19.52.29.zip](https://github.com/user-attachments/files/17521671/-2024-10-25_19.52.29.zip)

**Comment by kir-kir** [comment]
fixed in 02df55ba14b5aec5d75a8560e099d7a3968d5ad7
