### ISSUE TITLE
ImmersiveEngineering opens achievements and the game crashes

### ISSUE THREAD

**Issue by gdsfdsggd** [BluSpring/Kilt#49]
### Version information

Kilt-0.0.1+mc1.20.1+build.f64644

### Reproduction Steps

Open achievement

### Java version

java17

### Crash Report file

[错误报告-2024-10-26_11.31.55.zip](https://github.com/user-attachments/files/17528901/-2024-10-26_11.31.55.zip)

**Comment by BluSpring** [comment]
Should be fixed in 5a1105328753815a74e6f847c4d4c921574ad27d.
