### ISSUE TITLE
CWSM startup crash

### ISSUE THREAD

**Issue by End198** [BluSpring/Kilt#51]
### Version information

witherstormmod-1.20.1-4.2.1-all

### Reproduction Steps

1. Add mod to Minecraft
2. Start up Minecraft
3. Crash

### Java version

Java 17

### Crash Report file

[crash-2024-10-26_00.04.57-client.txt](https://github.com/user-attachments/files/17528997/crash-2024-10-26_00.04.57-client.txt)

### Additional information

Mod List:
architectury-9.2.14-fabric
fabric-api-0.92.2+1.20.1
fabric-language-kotlin-1.12.3+kotlin.2.0.21
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
Kilt-0.0.1+mc1.20.1+build.f64644
witherstormmod-1.20.1-4.2.1-all

**Comment by BluSpring** [comment]
Should be fixed by

**Comment by BluSpring** [comment]
Should be fixed by 344417841bc9fc14372823c7ed0e0b5442cc5941?

**Comment by PakinDeReal** [comment]
It's fixed
