### ISSUE TITLE
Curios API

### ISSUE THREAD

**Issue by Cartrigger** [BluSpring/Kilt#59]
### Version information

5.11.0+1.20.1

### Reproduction Steps

1: Add Curios
2: Start game
3: Go into Singleplayer
4: Open Inventory
5: Crash
6: Celebrate

### Java version

22

### Crash Report file

https://mclo.gs/L8f4geu

### Additional information

This is INGAME!

**Comment by BluSpring** [comment]
Fixed in d6eef67e91d85e6c4ed7942d704d4e08ffdf92c5.
