### ISSUE TITLE
Legendary Creatures Mod (Forge)

### ISSUE THREAD

**Issue by CaoTrongThang** [BluSpring/Kilt#64]
### Version information

Kilt-0.0.1+mc1.20.1+build.32fad1

### Expected Behavior

Mod can be loaded to the game

### Actual Behavior

The Legendary Creatures Mod didn't load into the game

### Reproduction Steps

1. Put the The Legendary Creatures Mod and run the Prism Launcher

### Java version

21

### Additional information

Here's the Crash Log https://mclo.gs/LyzWSs1
Mod's link: https://www.curseforge.com/minecraft/mc-mods/legendary-creatures

**Comment by BluSpring** [comment]
User error, you are missing GeckoLib.
