### ISSUE TITLE
[IceandFire + Citadel] Fonts missing

### ISSUE THREAD

**Issue by End198** [BluSpring/Kilt#65]
### Version information

iceandfire-2.1.13-1.20.1-beta-5 + citadel-2.6.0-1.20.1

### Expected Behavior

There should be fonts on the Minecraft main menu and other menus

### Actual Behavior

Text/fonts missing on Minecraft menus
![Screenshot 2024-10-27 164304](https://github.com/user-attachments/assets/55f103f0-c059-4c2c-9153-0d3bfe5ba82c)
![Screenshot 2024-10-27 164715](https://github.com/user-attachments/assets/1335ba5c-0bd1-47be-9d5e-7b707059325e)
![Screenshot 2024-10-27 164725](https://github.com/user-attachments/assets/77db91c0-875c-4cff-b05c-8ebb6d483037)

### Reproduction Steps

1. Add latest IceandFire and Citadel with other mods
2. Launch Minecraft
3. Missing Fonts

### Java version

Java 17

### Additional information

Mod List:
architectury-9.2.14-fabric
citadel-2.6.0-1.20.1
fabric-api-0.92.2+1.20.1
fabric-language-kotlin-1.12.3+kotlin.2.0.21
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
iceandfire-2.1.13-1.20.1-beta-5
Kilt-0.0.1+mc1.20.1+build.e50efb

**Comment by hedkne43rei0pow** [comment]
Btw there is an unofficial ice and fire fabric port
https://modrinth.com/mod/iceandfire-fabric

**Comment by BluSpring** [comment]
I'm pretty sure that port is unauthorized. I have my own Ice and Fire port - https://github.com/BluSpring/Ice_and_Fire-Fabric - but I received permission directly from Alex to port it to Fabric so long as I don't publish it to Modrinth/CurseForge.
![image](https://github.com/user-attachments/assets/e2616892-5692-460e-b2b9-2e6ce65ad8b4)

**Comment by BluSpring** [comment]
Fixed in 0ce564379438b3ac164622b06638d0dc2d9d905f.
