### ISSUE TITLE
Refined Storage, Block updates require a reload

### ISSUE THREAD

**Issue by Cartrigger** [BluSpring/Kilt#66]
### Version information

1.12.4

### Expected Behavior

Blocks to connect instantly and become bound with the controller, disk drives to instantly face the correct position

### Actual Behavior

Whenever using any blocks, to get connection, drives to show up and grids to become connected, a reload of the world is required, disk drives require a reload, then removal and replace to face correctly

### Reproduction Steps

1: Load the game
2: Join a world
3: Place a creative controller
4: Place a grid
5: Place Disk Drive
6: Place in Drive for storage
7: Reload

### Java version

22

**Comment by BluSpring** [comment]
Fixed in f2d4ea2347d829198b261a787f0c3a0a60dd63a2.
