### ISSUE TITLE
ImmersiveEngineering's use of the engineer's manual will still cause the game to crash

### ISSUE THREAD

**Issue by gdsfdsggd** [BluSpring/Kilt#69]
### Version information

Kilt-0.0.1+mc1.20.1+build.7657bc

### Reproduction Steps

Employ the manual for engineers

### Java version

java17

### Crash Report file

[错误报告-2024-10-28_17.29.07.zip](https://github.com/user-attachments/files/17540409/-2024-10-28_17.29.07.zip)

### Additional information

![2024-10-28 173738](https://github.com/user-attachments/assets/d93b43df-b443-426d-b988-1b91129ed83a)

**Comment by BluSpring** [comment]
How is the engineer's manual being used? It seems to work fine for me
![image](https://github.com/user-attachments/assets/addf8e52-701d-48a0-8ef1-1893f59d5697)

**Comment by gdsfdsggd** [comment]
https://github.com/user-attachments/assets/0025d125-a6cb-4717-866a-a2148c120ec5

**Comment by gdsfdsggd** [comment]
I just tried Kilt-0.0.1+mc1.20.1+build.00b7c5 version still crashed, and also tried to change the name to English, numbers, but no effect

**Comment by BluSpring** [comment]
.. i just figured out why i can't reproduce it, hold on

**Comment by gdsfdsggd** [comment]
OK
