### ISSUE TITLE
Alex's Caves - crash on startup

### ISSUE THREAD

**Issue by bmartin127** [BluSpring/Kilt#74]
### Version information

1.20.1-2.0.2

### Reproduction Steps

Install: Citadel, Alex's Caves, KiltMc
Launch the game and it crashes

### Java version

Java 17

### Crash Report file

[crash-2024-11-04_13.38.46-client.txt](https://github.com/user-attachments/files/17624755/crash-2024-11-04_13.38.46-client.txt)

**Comment by bmartin127** [comment]
My bad didnt see this was already reported

**Comment by BluSpring** [comment]
This crash isn't caused by Alex's Caves, or Kilt in general.

This crash is occurring because you're trying to use Sodium + Indium and VulkanMod.
