### ISSUE TITLE
Complicated Bees crashes due missing method in RegistryBuilder

### ISSUE THREAD

**Issue by unilock** [BluSpring/Kilt#78]
### Version information

0.0.1+mc1.20.1+build.2615e7

### Reproduction Steps

1. Install Fabric Loader + Kilt + [Complicated Bees](https://modrinth.com/mod/complicated-bees) + all dependencies
2. Start the game
3. Crash!!

### Java version

Java 21

### Crash Report file

latest.log: https://gist.github.com/unilock/3b161db52f3f0a67e8c926166f13a40e

(no crash report is generated)

**Comment by BluSpring** [comment]
Should be fixed in the newest update.
