### ISSUE TITLE
Minecolonies

### ISSUE THREAD

**Issue by Cartrigger** [BluSpring/Kilt#80]
### Version information

(MC) 1.20.1-1.1.732-snapshot, (S) 1.20.1-1.0.760-snapshot, (UI) 1.20.1-1.0.186-beta, (DO) 1.20.1-1.0.282-snapshot-universal

### Reproduction Steps

Place all required mods in mods folder
Start game
Crash

### Java version

21

### Crash Report file

https://mclo.gs/j0rGJFh

**Comment by BluSpring** [comment]
Duplicate of #70, add your crash report there.
