### ISSUE TITLE
JIJ mods do not work properly after remapped once and game restarted

### ISSUE THREAD

**Issue by Cartrigger** [BluSpring/Kilt#89]
### Version information

e4cef7

### Reproduction Steps

1. Start a mod with JIJ
2. Let remap
3. Quit game
4. Restart game
5. Crash due to "(NAMEHERE) failed to load!"

### Java version

21

### Crash Report file

https://mclo.gs/zueBrha

### Additional information

Regression from earlier versions.

**Comment by BluSpring** [comment]
This should have been fixed by 6bcec62249cf1b4afa3d2ba3921b838ec37a9528, can you try updating?

**Comment by Cartrigger** [comment]
i think i was a little dumb, sorry :(
